// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";
import type { VisualEdgeType } from "./VisualEdgeType";

export type Viewer = { states_names: Array<string>, state_pos: Array<Point>, edge_visuals: Array<VisualEdgeType>, };
