// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VisualEdgeType = "Straight" | "Angle" | { "Bezier": { start_dx: number, start_dy: number, end_dx: number, end_dy: number, } };
